In [1]:
import torch

In [2]:
T1 = torch.tensor([[1, 2, 3],
        		[4, 5, 6],
        		[7, 8, 9]])

In [3]:
T2 = torch.tensor([[10, 20, 30],
        		[40, 50, 60],
        		[70, 80, 90]])

In [7]:
torch.stack((T1,T2))[1]

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [9]:
s=torch.tensor([[2,3],[3,4]])

In [ ]:
y=[]

In [23]:
s=torch.rand([8,1])
y=[]
for i in range(3):
    y.append(s)

In [26]:
y.append(s)

In [30]:
torch.stack(y).shape

torch.Size([4, 8, 1])

In [31]:
torch.randint(2,8,10)

TypeError: randint() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
 * (int low, int high, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)


In [40]:
torch.randint(200,(5,8)).shape

torch.Size([5, 8])

In [48]:
a=torch.randint(200,(3,1))

In [39]:
torch.randint(200,(5,8))[4]

tensor([ 24,  24, 135,  52,  14,  44,  15,  40])

In [49]:
torch.nn.functional.one_hot(a)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])